baseURL = "http://example.org/"
languageCode = "zh-cn"
title = "HDU指北"
theme = "hugo-geekdoc"

pygmentsUseClasses = true
pygmentsCodeFences = true
timeout = 180000

# Geekdoc configuration
disablePathToLower = true
enableGitInfo = true
